const char* indexHtml = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n"
"    <title>Motor Control</title>\n"
"    <script>\n"
"    let currLeftPos = 0;\n"
"    let currRightPos = 0\n"
"    const moveMotor = (motorId, direction) => {\n"
"        let numSteps = document.getElementById(motorId === 0 ? 'lmotorsteps' : 'rmotorsteps').value\n"
"        console.log(numSteps)\n"
"        if(motorId === 0){\n"
"            currLeftPos += parseInt(numSteps)*direction;\n"
"            let currLeftPosText = document.querySelector(\"#lpos\")\n"
"            currLeftPosText.innerHTML = `Curr Left Motor Position: ${currLeftPos}`\n"
"        }\n"
"        else{\n"
"            currRightPos += parseInt(numSteps)*direction;\n"
"            let currRightPosText = document.querySelector(\"#rpos\")\n"
"            currRightPosText.innerHTML = `Curr Right Motor Position: ${currRightPos}`\n"
"        }\n"
"        let url = `http://192.168.0.100/move/${motorId}/${parseInt(numSteps)*direction}`\n"
"        const options = {\n"
"            method: \"POST\"\n"
"        }\n"
"        fetch(url, options)\n"
"    }\n"
"    const moveMotorSync = () => {\n"
"        let leftMotorPos = parseInt(document.getElementById('labspos').value)\n"
"        let rightMotorPos = parseInt(document.getElementById('rabspos').value)\n"
"        currLeftPos = leftMotorPos\n"
"        currRightPos = rightMotorPos\n"
"        let currLeftPosText = document.querySelector(\"#lpos\")\n"
"        let currRightPosText = document.querySelector(\"#rpos\")\n"
"        currLeftPosText.innerHTML = `Curr Left Motor Position: ${currLeftPos}`\n"
"        currRightPosText.innerHTML = `Curr Right Motor Position: ${currRightPos}`\n"
"        let url = `http://192.168.0.100/moveSync/${leftMotorPos}/${rightMotorPos}`\n"
"        const options = {\n"
"            method: \"POST\"\n"
"        }\n"
"        fetch(url, options)\n"
"    }\n"
"  </script>\n"
"  <style>\n"
"    .formContainer{\n"
"        display: flex;\n"
"    }\n"
"    p {\n"
"        margin: 0\n"
"    }\n"
"  </style>\n"
"  </head>\n"
"\n"
"  <body>\n"
"    <h1 id = \"intro\"> Stepper Motor Control</h1>\n"
"    <p id = \"lpos\">Curr Left Motor Position: 0</p>\n"
"    <p id = \"rpos\">Curr Right Motor Position: 0</p>\n"
"    <h2>Relative Motor Move</h2>\n"
"    <div style = \"display: flex; gap: 20px\">\n"
"        <div class =\"formContainer\">\n"
"            <p style=\"margin: 0px\">Left Motor Step Size:</p>\n"
"            <form >\n"
"                <input type = \"number\" id = \"lmotorsteps\">\n"
"            </form>\n"
"            <button onclick=\"moveMotor(0,1)\"> +</button>\n"
"            <button onclick=\"moveMotor(0,-1)\"> -</button>\n"
"        </div>\n"
"        <div class =\"formContainer\">\n"
"            <p style=\"margin: 0px\">Right Motor Step Size:</p>\n"
"            <form >\n"
"                <input type = \"number\" id = \"rmotorsteps\">\n"
"            </form>\n"
"            <button onclick=\"moveMotor(1,1)\"> +</button>\n"
"            <button onclick=\"moveMotor(1,-1)\"> -</button>\n"
"        </div>\n"
"    </div>\n"
"    <h2>Absolute Motor Position</h2>\n"
"    <div style = \"display: flex; gap: 20px\">\n"
"        <div class =\"formContainer\">\n"
"            <p style=\"margin: 0px\">Left Motor Position:</p>\n"
"            <form >\n"
"                <input type = \"number\" id = \"labspos\">\n"
"            </form>\n"
"        </div>\n"
"        <div class =\"formContainer\">\n"
"            <p style=\"margin: 0px\">Right Motor Positon:</p>\n"
"            <form >\n"
"                <input type = \"number\" id = \"rabspos\">\n"
"            </form>\n"
"        </div>\n"
"    </div>\n"
"    <button onclick=\"moveMotorSync()\">Go To</button>\n"
"  </body>\n"
"</html>\n";
